baseURL: "https://saimadhu27.github.io"
languageCode: "en-us"
title: "Madhuri"
theme: master

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD
canonifyURLs:  true

markup:
  goldmark:
    renderer:
      unsafe: true
